Add option to print LLVM IR (without debugging)
refu-lang/refu pull request #40
Opened 2017-02-23 22:38 UTC by axic

2017-02-24 11:30 UTC, LefterisJP requested changes

2017-02-24 11:30 UTC, LefterisJP commented on src/backend/llvm_ast.c
> +    char *mod_id = LLVMGetModuleIdentifier(ctx->llvm_mod, &mod_id_len);
This seems to be available only on the latest LLVM version (3.9). I do have it locally for example, but Travis tests use use LLVM version 3.7. I would like to be able to compile Refu with 3.7 too so perhaps use the module name that is already known and exists in this same function?

It should be the cstring `mod_name` found here: https://github.com/refu-lang/refu/pull/40/files#diff-10b12b4c46f372efd867280d766ffeadL375

If you do so then you should also move `RFS_POP()` to the end of the function, both in the happy case and the fail case.

2017-02-24 20:00 UTC, axic commented on src/backend/llvm_ast.c
> +    char *mod_id = LLVMGetModuleIdentifier(ctx->llvm_mod, &mod_id_len);
On my LLVM, `mod_name` always equals to `function_end` for some reason. Any ideas?

2017-02-24 21:21 UTC, LefterisJP commented on src/backend/llvm_ast.c
> +    char *mod_id = LLVMGetModuleIdentifier(ctx->llvm_mod, &mod_id_len);
@axic yes I know exactly why.

**TL;DR:**
So ... without going into too many details you will have to move `RFS_POP();` from line `382` to both the happy end and the unhappy end of the function. So move it to line 442 and to line 446.

**More details**: 
`RFstring`, the string we are using from the `rfbase` library is not null terminated. It was designed like that. `LLVM` needs null terminated strings. `rf_string_cstr_from_buff_or_die()` is one of the many functions that create temporary strings by utilizing a temporary buffer that is initialized in the beginning of the program. 

It saves the hustle of allocating and freeing strings but has the drawback that you have to remember where you initialized it with an `RFS_PUSH();` and when you want to stop using it use an `RFS_POP();`

In the current code the `RFS_POP();` is right after the LLVM module initialization call so after that point any other usage of the RFS buffer would overwrite it. Which happens somewhere down the line with the `function_end` label.

2017-02-25 13:27 UTC, axic commented
Rebased against #41.

2017-02-25 13:28 UTC, axic commented on src/backend/llvm_ast.c
> +    char *mod_id = LLVMGetModuleIdentifier(ctx->llvm_mod, &mod_id_len);
Fixed that bug independently in #41 and fixed this not duplicate the work.

2017-02-25 13:49 UTC, LefterisJP approved these changes

2017-02-25 14:51 UTC, merged

2017-02-25 14:52 UTC, LefterisJP commented
Thank you @axic. Much appreciated.